# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Referat',
        ),
    ]
