# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20170415_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referat',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='referat',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
